name = "music_40"
scenario = "."
sim_time = 600
save_data_for_cdf = true
runs = [1, 2, 3]
range = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 14, 16, 17, 18, 19, 20, 21, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 50, 55, 60, 65, 70, 75, 100]
range_format = '--dataRate={}Mbps'

constants = [
  'simtime600s',
  'vr_start_5',
  'disableTimestamp',
  'initcwnd10',
  'large_queues',
  'VR_max_delay_100',
  'delay1ms',
  'enableVr'
]

var_names = ['dataRate', 'vrVideoType', 'vrBitrateStrategy', 'vrStartBitrate', 'vrBitrateEstimation', 'discardTimer']

[[variables]] 
notCompressed_constantBitrate_20m = ['vrDefaultSettings', 'vrConstantBitrate', 'vrStartBitrate20m']
notCompressed_constantBitrate_10m = ['vrDefaultSettings', 'vrConstantBitrate', 'vrStartBitrate10m']
notCompressed_constantBitrate_5m = ['vrDefaultSettings', 'vrConstantBitrate', 'vrStartBitrate5m']
notCompressed_constantBitrate_2500k = ['vrDefaultSettings', 'vrConstantBitrate', 'vrStartBitrate2500k']
notCompressed_adaptiveBitrate_2500k_mean = ['vrDefaultSettings', 'vrStartBitrate2500k', 'vr_use_mean_bitrate']
notCompressed_adaptiveBitrate_2500k_max = ['vrDefaultSettings', 'vrStartBitrate2500k', 'vr_use_max_bitrate']

compressed_constantBitrate_20m = ['vrVideoCompressed', 'vrConstantBitrate', 'vrStartBitrate20m']
compressed_constantBitrate_10m = ['vrVideoCompressed', 'vrConstantBitrate', 'vrStartBitrate10m']
compressed_constantBitrate_5m = ['vrVideoCompressed', 'vrConstantBitrate', 'vrStartBitrate5m']
compressed_constantBitrate_2500k = ['vrVideoCompressed', 'vrConstantBitrate', 'vrStartBitrate2500k']
compressed_adaptiveBitrate_2500k_mean = ['vrVideoCompressed', 'vrStartBitrate2500k', 'vr_use_mean_bitrate']
compressed_adaptiveBitrate_2500k_max = ['vrVideoCompressed', 'vrStartBitrate2500k', 'vr_use_max_bitrate']

[[variables]]
discardEnabled = ['useDiscardTimer']
discardDisabled = []

[options]
antistarvation = '--enableAntistarvation=true'
enableVr = '--enableVr=true'
enableYt = '--enableYt=true'
enableWeb = '--enableWeb=true'
vrDefaultSettings = '--ns3::VideoStream::PcapRepository=/home/condorsync/sync/liubogoshchev/VR/pcaps_small/ --ns3::VideoStream::PcapBaseName=gopro'
vr_start_5 = '--ns3::VideoStream::StartPcapNum=5'
vrVideoCompressed = '--ns3::VideoStream::PcapRepository=/home/condorsync/sync/bankov/VR/pcaps/ --ns3::VideoStream::PcapBaseName=gopro_2018'
simtime600s = '--simulationTime=600s'
simtime300s = '--simulationTime=300s' 
simtime200s = '--simulationTime=200s'
vrConstantBitrate = '--ns3::VideoStream::ConstantBitrate=true'
vrStartBitrate20m = '--ns3::VideoStream::StartBitrate=20000000'
vrStartBitrate10m = '--ns3::VideoStream::StartBitrate=10000000'
vrStartBitrate5m = '--ns3::VideoStream::StartBitrate=5000000'
vrStartBitrate2500k = '--ns3::VideoStream::StartBitrate=2500000'

dataRate1Mbps = '--dataRate=1Mbps'
dataRate5Mbps = '--dataRate=5Mbps'
dataRate10Mbps = '--dataRate=10Mbps'
dataRate50Mbps = '--dataRate=50Mbps'
dataRate100Mbps = '--dataRate=100Mbps' 

delay100us = '--delay=100us'
delay1ms = '--delay=1ms'

vrMaxDelay500ms = '--ns3::VideoStream::MaxDelay=0.5'
vrMaxDelay100ms = '--ns3::VideoStream::MaxDelay=0.1'
disableTimestamp = '--ns3::TcpSocketBase::Timestamp=false'
initcwnd10 = '--ns3::TcpSocket::InitialCwnd=10'
singleWebPage = '--singleWebPage=true'
webPage100M = '--webPageSize=100000000'
webPage1M = '--webPageSize=1000000'
webPage100k = '--webPageSize=100000'
webPage10k = '--webPageSize=10000'
vr_use_max_bitrate = '--ns3::VideoStream::MaxBitrate=true'
vr_use_mean_bitrate = '--ns3::VideoStream::MaxBitrate=false'

vr_use_max_bitrate_compressed = '--ns3::VideoStream::MaxBitrate=true --ns3::VideoStreamSink::BitrateMode=MAX_COMPRESSED'
vr_use_mean_bitrate_compressed = '--ns3::VideoStream::MaxBitrate=true --ns3::VideoStreamSink::BitrateMode=MEAN_COMPRESSED'
large_queues = "--ns3::QueueBase::MaxSize=1000000p"
VR_max_delay_100 = '--ns3::VideoStream::MaxDelay=0.1'
useDiscardTimer = '--useDiscardTimer=true'
